### ISSUE TITLE
如何默认开启emoji

### ISSUE THREAD

**Issue by mathjiajia** [amzxyz/rime_wanxiang#29]

**Comment by dufei99** [comment]
我是配置user.yaml
```
var:
  last_build_time: 1740323073
  option:
    emoji: true
    full_shape: false
    tone_display: true
```
