### ISSUE TITLE
更換翻頁鍵為 [ ]，以詞定字為 - = 時，無法正確映射

### ISSUE THREAD

**Issue by bs10081** [amzxyz/rime_wanxiang#36]
![Image](https://github.com/user-attachments/assets/98803a47-209a-4046-ba43-b925669af8c3)

打超過一個字就會 [ ] 及 - = 皆為 **以詞定字**

**Comment by amzxyz** [comment]
你检查一下lua中是否有默认按键的逻辑，更新到仓库中最新版本了没有

**Comment by bs10081** [comment]
> 你检查一下lua中是否有默认按键的逻辑，更新到仓库中最新版本了没有

用的最新的版本，我也有用 Cursor 檢查過程式碼，確實都沒有寫死的部分

processors:
  - lua_processor@select_character
  - lua_processor@key_binder

這兩個也都確實都在裡面

這裡還需要麻煩排查，嗚嗚

**Comment by amzxyz** [comment]
更新一下6.0

**Comment by bs10081** [comment]
更新 6.0 以後，依舊還是無法使用 [ ] 進行翻頁，依舊會是以詞定字

**Comment by amzxyz** [comment]
default.yaml
```
    # 翻页 - =
    - { when: has_menu, accept: minus, send: Page_Up }
    - { when: has_menu, accept: equal, send: Page_Down }
    ```
前面加上井号

```
    # 翻页 [ ]
    # - { when: paging, accept: bracketleft, send: Page_Up }
    # - { when: has_menu, accept: bracketright, send: Page_Down }
```
去掉井号
打开方案文件
key_binder:
  import_preset: default  # 从 default.yaml 继承通用的
  # Lua 配置: 超级tips上屏按键
  tips_key: "period"   #修改时候去default找
  # Lua 配置: 以词定字（上屏当前词句的第一个或最后一个字），和中括号翻页有冲突
  select_first_character: "bracketleft"  # 左中括号 [
  select_last_character: "bracketright"  # 右中括号 ]
这里改成别的

这么点事

**Comment by bs10081** [comment]
default.yaml
```yaml
# 快捷键
key_binder:
  # Lua 配置: 以词定字（上屏当前词句的第一个或最后一个字），和中括号翻页有冲突
  select_first_character: "bracketleft" #  左中括号 [
  select_last_character: "bracketright" # 右中括号 ]
```

wanxiang.schema.yaml
```yaml
# 从 default 继承快捷键
key_binder:
  import_preset: default # 从 default.yaml 继承通用的
  # Lua 配置: 超级tips上屏按键
  tips_key: "period" #修改时候去default找
  # Lua 配置: 以词定字（上屏当前词句的第一个或最后一个字），和中括号翻页有冲突
  select_first_character: "bracketleft" # 左中括号 [
  select_last_character: "bracketright" # 右中括号 ]
```

那我認為 default.yaml 和 wanxiang.schema.yaml，相同的設定只保留一個，如果技術上需要保留兩個的話，README 需要備註，真沒想過以詞定字會在方案檔案裡面也有一份相同的程式碼

**Comment by bs10081** [comment]
實際測試將 wanxiang.schema.yaml 中的以詞定字註解後，依舊能發揮功能

```yaml
# 从 default 继承快捷键
key_binder:
  import_preset: default # 从 default.yaml 继承通用的
  # Lua 配置: 超级tips上屏按键
  tips_key: "period" #修改时候去default找
  # Lua 配置: 以词定字（上屏当前词句的第一个或最后一个字），和中括号翻页有冲突
  # select_first_character: "minus" # 左中括号 [
  # select_last_character: "equal" # 右中括号 ]
```

只需要保留 default.yaml 的以詞定字

```yaml

# 快捷键
key_binder:
  # Lua 配置: 以词定字（上屏当前词句的第一个或最后一个字），和中括号翻页有冲突
  select_first_character: "minus" # 左中括号 [
  select_last_character: "equal" # 右中括号 ]

  bindings:
    # Tab / Shift+Tab 切换光标至下/上一个拼音
    #- { when: composing, accept: Shift+Tab, send: Shift+Left }
    #- { when: composing, accept: Tab, send: Shift+Right }
    # Tab / Shift+Tab 翻页
    # - { when: has_menu, accept: Shift+Tab, send: Page_Up }
    # - { when: has_menu, accept: Tab, send: Page_Down }

    # Option/Alt + ←/→ 切换光标至下/上一个拼音
    - { when: composing, accept: Alt+Left, send: Shift+Left }
    - { when: composing, accept: Alt+Right, send: Shift+Right }

    # 翻页 - =
    # - { when: has_menu, accept: minus, send: Page_Up }
    # - { when: has_menu, accept: equal, send: Page_Down }

    # 翻页 , .
    # - { when: paging, accept: comma, send: Page_Up }
    # - { when: has_menu, accept: period, send: Page_Down }

    # # 翻页 [ ]
    - { when: paging, accept: bracketleft, send: Page_Up }
    - { when: has_menu, accept: bracketright, send: Page_Down }
```
