### ISSUE TITLE
始终没搞定斜杠/symbols的功能

### ISSUE THREAD

**Issue by harry10086** [amzxyz/rime_wanxiang#63]
重新安装了小狼毫0.17.0，用默认的朙月拼音，/fh就会出来符号。
但把万象拼音复制进去，什么都不改动，部署后/直接上屏。
测试半天感觉就是` __include: wanxiang_symbols:/symbol_table` 这个没有生效，我以为是少了`__include: wanxiang_symbols:/symbols`，加上去也不好使。
搞不定了，我觉得还是雾凇的v比较好用，/位置有点别扭，然后我把雾凇的symbols_v.yaml，v_filter.lua，拷过去，在wanxiang.schema.yaml加了：
```YAML
punctuator:
  symbols:
    __include: symbols_v:/symbols              # 从 symbols_v.yaml 导入配置
filters:
    - lua_filter@*v_filter                          # v 模式 symbols 优先
recognizer:
    patterns:  # 再增加方案专有的：
    punct: "^v([0-9]|10|[A-Za-z]+)$" 
```
总算可以用v了
